### PR TITLE
DateInput - Fix preset and mode selection

### LINKED ISSUE #283: DateInput - Fix preset dates and mode selection
### Context
While testing DateInput integration we noticed a strange behavior which didn't allow us to use `dates` prop correctly.

### Example
image

Typing the date manually was also broken:

image

### Description
This Pull Request reverts some of our latests changes on DateInput component in order to fix those issues.

### Requirements
- [x] `dates` prop is prioritized over current preset's dates
- [x] Typing the date manually keeps the selection mode (period or single)

### PR DESCRIPTION
**Pull request by vagnervst**
## Context
Dates were not changing when using `dates` prop, also, typing the date manually caused the selection mode to change unexpectedly. So this PR reverts some of our latests changes to fix that. 

## Checklist
- [x] Using `dates` prop works as expected
- [x] Typing is now possible

## Linked Issues
- [x] Resolves #283

## How to test
1. Link this branch with pilot's `master`
2. Use DateInput from Transactions Search page

### CODE REVIEW

File: src/DateInput/index.js [hunk 1]
```diff
@@ -152,17 +152,19 @@ class DateInput extends React.Component {
...
+      const selectedPreset = presetChanged
         ? propsSelectedPreset
         : currentSelectedPreset
 
       const preset = findPreset(selectedPreset, presets)
       const presetDates = getDatesFromPreset(preset)
 
       this.setState({ // eslint-disable-line react/no-did-update-set-state
-        dates: momentToText(presetDates || dates),
+        dates: momentToText(presetChanged
```
Comment (Deivis) [inline src/DateInput/index.js]: This ternary condition could be in a variable outside of the object declaration.

File: src/DateInput/index.js [hunk 2]
```diff
@@ -152,17 +152,19 @@ class DateInput extends React.Component {
...
+          ? presetDates
+          : dates),
         selectedPreset,
-        selectionMode: preset && preset.mode,
```
[the remark this answers is not in the document]
Comment (vagnervst) [reply src/DateInput/index.js]: Opsie! Fixed that

**Comment by vagnervst** [comment]
@Deivis Pushed a fix for the mode selection and I also noticed we were running this componentDidUpdate everytime (even when prop `selectedPreset` hasn't changed), which was preventing the text input from updating when choosing another preset (updating only state's `selectedPreset`)

So I changed the equality condition to compare only the `selectedPreset` prop. Please check if that makes sense :slightly_smiling_face:

File: src/DateInput/index.js [hunk 3]
```diff
@@ -150,17 +149,21 @@ class DateInput extends React.Component {
     const isSameStart = receivedStart && receivedStart.isSame(currentStart, 'day')
     const isSameEnd = receivedEnd && receivedEnd.isSame(currentEnd, 'day')
 
-    if (!equals(prevProps, this.props) && (!isSameStart || !isSameEnd)) {
-      const prevPropsSelectedPreset = prevProps.selectedPreset
-      const selectedPreset = prevPropsSelectedPreset !== propsSelectedPreset
+    const prevPropsSelectedPreset = prevProps.selectedPreset
+    const presetChanged = prevPropsSelectedPreset !== propsSelectedPreset
+    if (presetChanged && (!isSameStart || !isSameEnd)) {
+      const selectedPreset = presetChanged
```
Comment (rsmelo) [inline src/DateInput/index.js]: in this point of execution `presetChanged` will always be true and this ternary operator is not needed

File: src/DateInput/index.js [hunk 4]
```diff
@@ -150,17 +149,21 @@ class DateInput extends React.Component {
...
         ? propsSelectedPreset
         : currentSelectedPreset
 
       const preset = findPreset(selectedPreset, presets)
       const presetDates = getDatesFromPreset(preset)
+      const propsOrPresetDates = presetChanged
```
Comment (rsmelo) [inline src/DateInput/index.js]: in this point of execution `presetChanged` will always be true and this ternary operator is not needed

Comment (vagnervst) [reply src/DateInput/index.js]: Well noticed, fixed both comments with the same problem

**Comment by vagnervst** [comment]
I wasn't able to replicate the performance issue here :thinking: 

Peek 2019-07-18 17-46

**Comment by rsmelo** [comment]
@vagnervst i tested it again and this performance issue occurs only in Firefox =(

**Comment by vagnervst** [comment]
@rsmelo Thats odd, I noticed it also happens on `master` branch, any way we can debug on that? :worried:

**Comment by rsmelo** [comment]
Maybe a better option is create a new issue to solve the performance issue in a future PR

**Comment by vagnervst** [comment]
@rsmelo Seems fair. Using Firefox's Performance tool, It looks like there is a `ComponentWillReceiveProps` call that is taking a lot of time, maybe we can use it to solve the performance issue in the future
